<?php

/**
 * @file
 * Provides Drupal integration with the Juicebox gallery library.
 */


/**
 * Implements hook_menu().
 */
function juicebox_menu() {
  $items = array();
  // Add menu item that produces the "config.xml" data that is linked to a
  // specific view.
  $items['juicebox/xml/%'] = array(
    'title' => 'Juicebox XML from view',
    'description' => '',
    'page callback' => 'juicebox_page_xml',
    'page arguments' => array(2),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


// Callback for the menu item that generates Juicebox XML linked to a specific
// page. This simply fetches the cached XML that was already created when the
// gallery embed code was rendered.
function juicebox_page_xml() {
  // We don't always know exactly how many args are being passed, so we have to
  // fetch them programmatically with func_get_args()
  $args = func_get_args();
  // Reconstruct the cid that holds the xml related to this request.
  foreach ($args as $arg) {
    $cid .= '/' . $arg; 
  }
  $xml = cache_get($cid, 'cache_juicebox');
  // If we did not find a value from the cache take any special actions needed.
  if (!$xml) {
    // Make it clear to Juicebox that we don't have any XML to give it.
    drupal_add_http_header('Status', '404 Not Found');
    // @TODO: Add logic to build the XML if it for some reason it was not in the
    // cache and can actually be built based on the args passed. Under certain
    // caching conditions I suppose it MIGHT be possible for the embed code to
    // be cached in cache_page (meaning the XML is not rebuilt as part of the
    // main gallery page reuest) while the xml is NOT in cache_page OR in
    // cache_juicebox.
  }
  else {
    drupal_add_http_header('Content-Type', 'text/xml');
    print($xml->data);
  }
}


/**
 * Implements hook_views_api().
 */
function juicebox_views_api() {
  $path = drupal_get_path('module', 'juicebox');
  return array(
    'api' => 2.0,
  );
}


// Render the Juicebox XML from a view object that makes use of our view plugins 
function juicebox_render_xml_from_view($view) {
  $options = $view->style_options; 
  $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n";
  $xml .= '<juiceboxgallery' . "\n";
  $xml .= '  galleryTitle="' . $view->human_name .'"' . "\n";
  $xml .= '  galleryWidth="' . $view->style_options['width'] .'"' . "\n";
  $xml .= '  galleryHeight="' . $view->style_options['height'] .'"' . "\n";
  $xml .= '  ' . $view->style_options['advanced']['config'] . "\n";
  $xml .= '>' . "\n";
  foreach ($view->result as $row_index => $row) {
    // Get the main image source
    $field_image_name = "field_{$options['image_field']}";
    $field_image_uri = $row->{$field_image_name}[0]['raw']['uri'];
    if (!empty($options['image_field_style'])) {
      $image_src = image_style_url($options['image_field_style'], $field_image_uri);
    }
    else {
      $image_src = file_create_url($field_image_uri);
    }
    // Get the thumbnail source
    $field_thumb_name = "field_{$options['thumb_field']}";
    $field_thumb_uri = $row->{$field_thumb_name}[0]['raw']['uri'];
    if (!empty($options['thumb_field_style'])) {
      $thumb_src = image_style_url($options['thumb_field_style'], $field_thumb_uri);
    }
    else {
      $thumb_src = file_create_url($field_image_uri);
    }
    // We use $view->render_field in the code below to provide an easy way
    // to get the raw rendered output for each individual non-image field. This
    // gives us a consistent result no matter what the field type is. However, 
    // there may more efficient ways to do this (sans a "render" call). For now
    // while using $view->render_field, note that we have to be sure that the 
    // CURRENT row index is set on the main view object, otherwise rendering 
    // errors may result in certain situations.
    $view->row_index = $row_index;
    $title = $view->render_field($options['title_field'], $row_index);
    $caption = $view->render_field($options['caption_field'], $row_index);
    // Add each image to the xml
    $xml .= '  <image imageURL="' . $image_src . '"' . "\n";
    $xml .= '    thumbURL="' . $thumb_src . '"' . "\n";
    $xml .= '    linkURL="' . $image_src . '"'. "\n";
    $xml .= '    linkTarget="_blank">'. "\n";
    $xml .= '    <title>' . $title . '</title>'. "\n";
    $xml .= '    <caption><![CDATA[' . $caption . ']]></caption>' . "\n";
    $xml .= '  </image>'. "\n";    
  }
  $xml .= '</juiceboxgallery>';
  return $xml;
}


// Helper function to get the src value from the first img tag in the given 
// markup
function juicebox_get_img_src($markup) {
  $img_src = '';
  $parser = xml_parser_create();
  xml_parse_into_struct($parser, $markup, $values);
  foreach ($values as $key => $val) {
    if ($val['tag'] == 'IMG') {
      $img_src = $val['attributes']['SRC'];
      break;
    }
  }
  return $img_src;
}


/**
 * Implements hook_libraries_info().
 */
function juicebox_libraries_info() {
  $libraries['juicebox'] = array(
    'name' => 'Juicebox',
    'vendor url' => 'http://www.juicebox.net/',
    'download url' => 'http://www.juicebox.net/download/',
    'version arguments' => array(
      'file' => 'juicebox.js',
      'pattern' => '/Juicebox-([0-9a-zA-Z\.\ -]+)/',
      'lines' => 5,
    ),
    'files' => array(
      'js' => array('juicebox.js'),
    ),
 );
 return $libraries;
}


/**
 * Implements hook_help().
 */
function juicebox_help($path, $arg) {
  
}

/**
 * Implements hook_flush_caches().
 */
function juicebox_flush_caches() {
  if (db_table_exists('cache_juicebox')) {
    return array('cache_juicebox');
  }
}
